---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: peppr-static-test
rules:
  - apiGroups:
      - peppr.dev
    resources:
      - pepprstores
    verbs:
      - create
      - get
      - patch
      - watch
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - patch
      - create
  - apiGroups:
      - ''
    resources:
      - namespaces
    verbs:
      - watch
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - watch
