---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pepprstores.peppr.dev
spec:
  conversion:
    strategy: None
  group: peppr.dev
  names:
    kind: pepprStore
    listKind: pepprStoreList
    plural: pepprstores
    singular: pepprstore
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          data:
            additionalProperties:
              type: string
            type: object
        type: object
    served: true
    storage: true
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: peppr-system
  name: peppr-system
spec: {}

